INSERT INTO roles (name)
SELECT 'ROLE_OPERATOR'
WHERE NOT EXISTS (
    SELECT 1 FROM roles WHERE name = 'ROLE_OPERATOR'
);

INSERT INTO roles (name)
SELECT 'ROLE_MODERATOR'
WHERE NOT EXISTS (
    SELECT 1 FROM roles WHERE name = 'ROLE_MODERATOR'
);
